apiVersion: v1
kind: Pod
metadata:
  name: dbdump-inspector
  namespace: fiszkilab2
spec:
  containers:
  - image: busybox
    name: dbdump-inspector
    command: ["tail"]
    args: ["-f", "/dev/null"]
    volumeMounts:
    - mountPath: /pvc
      name: pvc-mount
  volumes:
  - name: pvc-mount
    persistentVolumeClaim:
      claimName: fiszki-dbdump-pvc