apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: fiszkilab2
  labels:
    app: fiszki-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiszki-backend
  template:
    metadata:
      labels:
        app: fiszki-backend
    spec:
      containers:
      - name: fiszki-backend
        image: backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: backend-port
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: fiszki-backend-cm
              key: databaseUrl
        - name: logging
          valueFrom:
            configMapKeyRef:
              name: fiszki-backend-cm
              key: logging
        volumeMounts:
        - mountPath: "/usr/app/log"
          name: fiszki-backend-pv
      volumes:
      - name: fiszki-backend-pv
        persistentVolumeClaim:
          claimName: fiszki-backend-pvc