apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: fiszkilab2
  labels:
    app: fiszki-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiszki-backend
  template:
    metadata:
      labels:
        app: fiszki-backend
    spec:
      containers:
      - name: fiszki-backend
        image: backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: backend-port