apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace}}
  name: {{ .Release.Name }}-db-svc
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017