apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace}}
  name: {{ .Release.Name }}-backend-svc
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      nodePort: {{.Values.backend.service.nodePort}}
