apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fiszki-backend-pvc
  namespace: fiszkilab2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi